### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by primozcigler** [GaryJones/Gamajo-Registerable#4]
Hi @GaryJones 

First of all thank you for amazing job with this repo. I always love to see someone taking a plunge and going for more standardized way of implementing things.

I stumbled upon your registerable in the portfolio-post-type plugin, now I'd like to include it in my own project. What I don't like is to copy/paste the code, I prefer using the composer as a package manager. Is it possible to make this project composer-ready (using packagist)? I can prepare the PR if you want to.

Thanks!

**Comment by primozcigler** [comment]
I am also thinking that the directory structure and names of the files should be changed, as I would like to apply the PSR-4 autoloader.

Another thing: I can only see 1 release (1.0.0), but there seems to be quite some changes afterward that tag.

If you think this is too much, I can still fork the project and make the required changes in the new repo.

**Comment by GaryJones** [comment]
Hi @primozcigler,

I'm open for the `composer.json`, but it may be better long term if you maintain your own fork. I'm slowly moving away from having Gamajo Registerable as a site core mu-plugin, and will be transitioning to @schlessera's https://github.com/brightnucleus/custom-content package instead.

**Comment by primozcigler** [comment]
Hi @GaryJones 

Thank you for your fast reply. I didn't know about the https://github.com/brightnucleus/custom-content . I will give it a try before I go working your repo, since it might satisfy all my needs.

All the best!
Primoz from ProteusThemes
